name: api_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  rflutter_alert: ^1.0.3
  google_maps_flutter: 0.5.21+15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true




  